# Generated by Django 5.2.6 on 2025-10-07 06:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopper_first_name', models.CharField(blank=True, default='', help_text='First name of shopper.', max_length=255)),
                ('shopper_name', models.CharField(blank=True, default='', help_text='First name of shopper.', max_length=255)),
                ('shopper_email', models.EmailField(help_text='Shopper email', max_length=254)),
                ('shopper_address', models.CharField(help_text='Shopper address', max_length=255)),
                ('shopper_postal_code', models.CharField(help_text='postal code of shopper', max_length=16)),
                ('shopper_city', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('CN', 'China'), ('JP', 'Japan'), ('IN', 'India'), ('BR', 'Brazil'), ('RU', 'Russia'), ('AU', 'Australia'), ('ZA', 'South Africa'), ('NG', 'Nigeria'), ('EG', 'Egypt'), ('KE', 'Kenya'), ('MX', 'Mexico'), ('AR', 'Argentina'), ('KR', 'South Korea'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('SG', 'Singapore'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('PL', 'Poland'), ('TR', 'Turkey'), ('MA', 'Morocco'), ('DZ', 'Algeria'), ('TN', 'Tunisia'), ('MG', 'Madagascar')], help_text='Country shopper', max_length=255)),
                ('shopper_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('product_title', models.CharField(max_length=255)),
                ('product_id', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
