# Generated by Django 5.2.6 on 2025-10-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shopper_cost',
        ),
    ]
