# Generated by Django 5.2.6 on 2025-10-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_old_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('paid', 'Payé')], default='unpaid', max_length=10, verbose_name='Statut de paiement'),
        ),
    ]
