version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    restart: unless-stopped
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data  

  redis:
    image: redis:6.2
    restart: unless-stopped
    expose:
      - '6379'

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    volumes:
      - ./rootapp:/code/rootapp
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis

volumes:
  postgres_data:
